### ISSUE TITLE
Race condition when starting a new game

### ISSUE THREAD

**Issue by nbelikov** [TobiasBielefeld/Simple-Solitaire#100]
Steps to reproduce:
1. Start a game of Spider (others will probably work too)
2. Tap Menu -> Start new game. An animation will begin, with the cards on the table stacks moving to the main stack
3. Quickly, before this animation ends and the animation of dealing cards from the main stack back to the tableau begins, tap Home (circle) button.
4. Tap Recent apps (square) button and close (swipe right or left) Simple Solitaire Collection
5. Open the application again. 

After that, the game should be in a broken state, where the tableau is empty, there is only one pack in the main stack, which however can be dealt repeatedly until you run out of cards, at which point an exception is raised.

**Comment by nbelikov** [comment]
Forgot to say, the app version is 3.10.1 from Play Store, and my phone runs Android 6.0.1.

**Comment by TobiasBielefeld** [comment]
Not really a race condition, my code just didn't handle the case if the app gets killed before calling a handler for card dealing :D 
Thanks for notifying me, it is fixed in the new app version 3.10.2
