### ISSUE TITLE
Klondike freezes

### ISSUE THREAD

**Issue by ibinshoid** [TobiasBielefeld/Simple-Solitaire#101]
Since i updated from 3.9.2 to 3.10.1 Klondike (and maybe the other games too) sometimes shows only one black card and isn't usable. After erasing the app data in the android settings it works fine for some time.
Android is 6.0

![screenshot_20180127-114255](https://user-images.githubusercontent.com/16139662/35528427-b22539bc-0525-11e8-9460-764533c9dc65.png)

**Comment by TobiasBielefeld** [comment]
Hi! Sorry for this issue. The changes were intended to resolve other kinds of loading issues... Well I released a new app version. Can you test if it is fixed there?

**Comment by ibinshoid** [comment]
Tested it a while now, no problems anymore.
