### ISSUE TITLE
[FreeCell] Not all starting positions can get you the maximum score

### ISSUE THREAD

**Issue by Nadrieril** [TobiasBielefeld/Simple-Solitaire#102]
When the starting position includes kings already on the bottom of their stack, it is impossible to get the 20 points bonus that comes from moving that king to a free space, since the king is already on a free space. Thus the total score at the end of the game (not counting time bonus) cannot reach the expected 3200.

**Comment by TobiasBielefeld** [comment]
oh thanks! I will fix this in the next time

**Comment by TobiasBielefeld** [comment]
Fixed in app version 3.11 !
