### ISSUE TITLE
Option to disable undo score penalty ?

### ISSUE THREAD

**Issue by Nadrieril** [TobiasBielefeld/Simple-Solitaire#105]
I'd quite like an option to disable the score penalty from hitting undo. I understand it makes sense for games like Klondike where undo can be used to know about the face-down cards, which is kinda cheating, but in FreeCell for example, undo does not change much.

**Comment by TobiasBielefeld** [comment]
Sure, I'll add a global option for that :)

**Comment by Nadrieril** [comment]
Thanks :)

**Comment by TobiasBielefeld** [comment]
The new app version 3.11 contains this now. You find the option in the expert settings. Sorry for the delay!

**Comment by Nadrieril** [comment]
Thank you very much !
