### ISSUE TITLE
Wrong labels for number of cards to draw

### ISSUE THREAD

**Issue by pageer** [TobiasBielefeld/Simple-Solitaire#106]
Under Settings > Games, the settings for "Number of cards to draw" show the wrong labels. They should be "Draw 1" and "Draw 3", but instead both choices say "Draw 1". This applies to Canfield, Klondike, and Vegas. Note that the choices do seem to toggle between 1 and 3 cards, so the setting does work. You just have to guess which one is for three.

**Comment by TobiasBielefeld** [comment]
thanks for noticing! I'll fix it

**Comment by TobiasBielefeld** [comment]
Fixed in app version 3.11, sorry for the delay!
