### ISSUE TITLE
Vegas-Flipping deck

### ISSUE THREAD

**Issue by Korpip** [TobiasBielefeld/Simple-Solitaire#115]
I am unable to flip the deck after a tapping my way through it on my Nexus 7 Flo.  It works on my Moto X Play Lux.  Both with draw 1 or 3.

**Comment by Korpip** [comment]
So.  You know those days where you wake up a little dumb?  It is Klondike I play on my cell not Vegas.  I just selected the wrong one.  I am so sorry to bother you.

**Comment by TobiasBielefeld** [comment]
No problem, I'll close this then :)
