### ISSUE TITLE
Napoleon's Tomb

### ISSUE THREAD

**Issue by bbenne10** [TobiasBielefeld/Simple-Solitaire#116]
Firstly, thank you for this collection! I find it tremendously addictive! I would love this even more if an implementation of Napoleon's Tomb could be added. Having looked over the Klondike implementation, it looks like Napoleon's Tomb would be pretty simple to implement if you were familiar with the code. Unfortunately, I've got little free time to become familiar and open a PR. 

The ruleset for this game can be found at: http://www.pahnation.com/how-to-play-napoleons-tomb

If there's anything else I can do to better describe the game, please let me know. If I happen to fund some free time, I may look at implementing this and issue a pull request, but I wanted to request here to see if this interested anyone else! Thanks!

**Comment by TobiasBielefeld** [comment]
Adding this game doesn't seem to be difficult. I will work on it. You don't need to do it yourself :)

**Comment by bbenne10** [comment]
I just noticed some progress for this ticket was made in #124. Thank you!

I'll be more than happy to test it out once I can get a new build. I'm not currently set up for Android builds, so it might have to be after another version bump.

**Comment by bbenne10** [comment]
In general, the ruleset seems correct. U would only complain about the tableaus starting out populated. The ruleset I am familiar with leaves them unpopulated and only allows one flip through the reserve. This makes the game MUCH more difficult, but gives the user the flexibility to deal with it a bit better.

**Comment by TobiasBielefeld** [comment]
Okay I changed the rules accordingly and also made the layout a bit more round. I released a new app version v3.12 for that. Hopefully now it is alright.

**Comment by bbenne10** [comment]
I've been playing for a few days now and everything looks great! Closing. Thank you!
