### ISSUE TITLE
Thanks for the updates and the app itself.

### ISSUE THREAD

**Issue by StygianBlues** [TobiasBielefeld/Simple-Solitaire#117]
I have no other way of contacting you, so I opened an Issue.  Thank you for the updates of late, with bug fixes.  I really appreciate the time you find to maintain this app and listing it on F-Droid.  I use it daily.  Feel free to close this Issue after reading this.

**Comment by TobiasBielefeld** [comment]
Thank you for the nice words, I am very happy to receive such feedback :) I put my e-mail address in the readme of this repo for future purposes.
