### ISSUE TITLE
2/4 color appearance should be per-game

### ISSUE THREAD

**Issue by waldner** [TobiasBielefeld/Simple-Solitaire#118]
Or at least it should be possible to override the setting on a per-game basis. If you happen to alternate between playing a game with 2-color deck and another with 4-color deck, every time you switch you have to change the global setting first.

**Comment by TobiasBielefeld** [comment]
I will work on that!

**Comment by TobiasBielefeld** [comment]
My new release 3.13 has finally the ability to set up the Appearance setting on per-game basis! (Sorry for the long delay)

**Comment by waldner** [comment]
Thanks!
