### ISSUE TITLE
Klondike reset score when collapsing the menu

### ISSUE THREAD

**Issue by MDosky** [TobiasBielefeld/Simple-Solitaire#122]
Hi, I noticed that when I collapse the menu in Klondike the score is set to 195.

![2018-04-20 17 51 33](https://user-images.githubusercontent.com/976087/39041427-b32ae3ba-44c3-11e8-92b1-b94c943b3e44.png)
![2018-04-20 17 51 40](https://user-images.githubusercontent.com/976087/39041432-b58ee66a-44c3-11e8-81fa-7f2feb3fb087.png)

I'm using a Pixel 1 (Android 8.1.0), the version is 3.11.2 installed from F-Droid.

**Comment by TobiasBielefeld** [comment]
Thanks for showing this! The new app version should fix this.
