### ISSUE TITLE
Klondike zoom out when the screen is locked and unlocked

### ISSUE THREAD

**Issue by 4fff618** [TobiasBielefeld/Simple-Solitaire#123]
When Klondike game is running and portrait mode is forced, if you lock the screen with the game open and then unlock the screen, the game area is reduced until a card is moved, then it come back at the normal size.

I attach a screenshot with the problem: https://i.imgur.com/G8iMqIf.jpg

Game version: 3.11.3
Installed from F-Droid.
Android 8.0 Stock
Motorola Z play

**Comment by TobiasBielefeld** [comment]
thanks for reporting this, it will be fixed!

**Comment by 4fff618** [comment]
You're welcome!. Your game is the best cards game and also is open source, i love it!.

**Comment by TobiasBielefeld** [comment]
Thanks again :) The fix is now in the new app version 3.12. (F-Droid will take some time to build it)
