### ISSUE TITLE
[wish] remove scoring option

### ISSUE THREAD

**Issue by zeroheure** [TobiasBielefeld/Simple-Solitaire#157]
I think title says all :  I don't like scoring in solitaire games, so an option to hide or remove it would make me happy ! :-)

BTW thanks for all the work you do.

**Comment by tryton-vanmeer** [comment]
Simple-Solitaire currently has an option to hide the score as of v3.9. It's in Settings->Appearance, under the background and text colour.

**Comment by zeroheure** [comment]
Ok found it! 
The french translation is a bit confusing : instead of "masquer les points" it should be "masquer le score". Because "points" can be understood as the card number.
