### ISSUE TITLE
Allow moving multiple cards in Fourty&Eight

### ISSUE THREAD

**Issue by verdulo** [TobiasBielefeld/Simple-Solitaire#18]
Please allow moving multiple cards in the game Fourty&Eight if free tableau fields are available - similar feature is already available for FreeCell.

Maybe even remove option to disable that behaviour in FreeCell, because it doesn't affects rules of gameplay in any way.

**Comment by TobiasBielefeld** [comment]
Sure I add it to the game :) And yes, you are right, I gonna remove the option.

I am also adding the double tap feature, so i gonna test everything for a while for problems and then make the new release :)
