### ISSUE TITLE
Android 12: screen freezing, system crashing

### ISSUE THREAD

**Issue by Anke** [TobiasBielefeld/Simple-Solitaire#180]
Hallo Tobias,
Is there anything we can do to persuade you keep maintaining this wonderful solitaire collection?
Everyday time I'm playing Klondike for a while the screen freezes and the whole system crashes. I can pick up where I left off after a reboot. I reinstalled the app, but no change. (Murena One with /e/OS 1.14 - Android 12)
Gruß,
Anke

**Comment by TacoTheDank** [comment]
Are you sure this has anything to do with the Solitaire app itself? This sounds like a system issue.

**Comment by Anke** [comment]
Until a few days ago all crashes happened while i was playing cards (sounds as if I had too much spare time...), but recent crashes happened using other apps. 

So you're probably right and my system needs a factory reset.

Thank you.
