### ISSUE TITLE
Improve statistics

### ISSUE THREAD

**Issue by verdulo** [TobiasBielefeld/Simple-Solitaire#19]
Please display in statistics window total number of games and percentage of wins.

**Comment by TobiasBielefeld** [comment]
I already planned that for a while, I'll add it in the next release :D

**Comment by TobiasBielefeld** [comment]
So everything should work now. I added some new Strings:
In strings-statistics are 2 new strings for the total number of games and percentage.
strings-settings contain 4 new strings to deactivate the limited re-deals for Forty&Eight and Pyramid
I copied the part about the multiple card movement from the freecell manual entry to the forty&eight entry

I would be happy if you could translate the new strings and check the forty&eight entry :)

**Comment by verdulo** [comment]
I checked the manual and it's correct.

**Comment by TobiasBielefeld** [comment]
Thanks :D
