### ISSUE TITLE
Use Material Design Icons

### ISSUE THREAD

**Issue by stefan-niedermann** [TobiasBielefeld/Simple-Solitaire#24]
Nice project. The bottom bar looks a bit old-shool.
What do you think about changing the activity more to a material design?
The bar could be on the top and display [Material Design Icons](https://materialdesignicons.com). So the overall-feeling would be more modern and well-known by the user.

Regards

**Comment by TobiasBielefeld** [comment]
Sure i can materialize the icons, thanks for the link :D But I think the bottom is a better place for the menu bar, because it's way easier to access on bigger phones than a top bar.

**Comment by stefan-niedermann** [comment]
Okay :) looking forward

**Comment by TobiasBielefeld** [comment]
So i use these icons, do you think they are okay?
<div align="center"><img width="45%" src="https://github.com/TobiasBielefeld/Simple-Solitaire/blob/master/Pictures/newIcons.png?raw=true"</img></div>

**Comment by stefan-niedermann** [comment]
Looks much more natural imho :) the choice is yours of course.

About bar position top/bottom: The primary action a user does is to drag 'n' drop some cards - so if they are better reachable it's more important than the actions which are used not very often.
just in my humble opinion ;)

regards

**Comment by TobiasBielefeld** [comment]
Well I now added an option to change the position between top/bottom in portrait mode and left/right in landscape mode, this should be the best solution :D
