### ISSUE TITLE
Bug in 'Aces Up' with double tap

### ISSUE THREAD

**Issue by verdulo** [TobiasBielefeld/Simple-Solitaire#30]
Version 3.2, when I double tapped the ace, it has been moved against the rules into discard stack.
![screenshot_2017-02-11-09-11-09](https://cloud.githubusercontent.com/assets/16842967/22852749/5560223e-f043-11e6-888d-5c995a5cc7f0.png)

**Comment by TobiasBielefeld** [comment]
Thanks for the report :) Fixed it.
