### ISSUE TITLE
4-color deck?

### ISSUE THREAD

**Issue by ToNIX-** [TobiasBielefeld/Simple-Solitaire#33]
Hi! Thanks for the great games. Some games would be a lot easier with a 4-color deck, just like poker (clubs are green and diamonds are blue). Is this something that could be implemented?

**Comment by TobiasBielefeld** [comment]
So do you talk about card themes with additional colors? Or would it also require some changed rules?

**Comment by ToNIX-** [comment]
Just the theme!

**Comment by TobiasBielefeld** [comment]
Okay, then i will work on it :)

**Comment by TobiasBielefeld** [comment]
Okay, now every card theme is also available in a 4 color version. There will be a new settings entry under "Apperance" to enable it. After working at the last issue, i will release the new app version :) Here is a little preview:
<div align="center"><img width="45%" src="https://github.com/TobiasBielefeld/Simple-Solitaire/blob/master/Pictures/screenshots/smartphone/smartphone_4_color_theme.png?raw=true"</img></div>

**Comment by ToNIX-** [comment]
Wow that looks amazing! Nice work :)

**Comment by TobiasBielefeld** [comment]
Thanks :D
