### ISSUE TITLE
Date in high scores

### ISSUE THREAD

**Issue by alekksander** [TobiasBielefeld/Simple-Solitaire#34]
Wouldn't it be good to have date stamp in high score board?

**Comment by TobiasBielefeld** [comment]
sure, i will add it next week :)

**Comment by alekksander** [comment]
thank You.
if You think it's a good idea, also time stamp would be appreciated.

**Comment by TobiasBielefeld** [comment]
okay, i'll try that too :D

**Comment by TobiasBielefeld** [comment]
So this is my attempt for the new high score list. I will release a new app version after working on the other issues :)
<div align="center"><img width="45%" src="https://github.com/TobiasBielefeld/Simple-Solitaire/blob/master/Pictures/screenshots/smartphone/smartphone_high_socores.png?raw=true"</img></div>

**Comment by alekksander** [comment]
nothing to complain about :)
thanks! finally i will be able to tell if im beter at game after 5 beers 03:00 friday, or when sober any other day ;)

**Comment by TobiasBielefeld** [comment]
:D yes the date and time are formatted according to the locale.
