### ISSUE TITLE
[Feature Request] Tap to select/move card

### ISSUE THREAD

**Issue by soaringowl2145** [TobiasBielefeld/Simple-Solitaire#35]
Is it possible that you can please add a way to tap once on a card and then move it by taping on the place where the card should be moved to like the way other apps handle this?

Thanks!

**Comment by TobiasBielefeld** [comment]
i will work on it :)

**Comment by soaringowl2145** [comment]
Thanks!

**Comment by TobiasBielefeld** [comment]
Okay, i finally added it and released the new app version (may take some time until it reaches the F-Droid Store). If you find something that should be done differently, tell me and I'll change it :)

**Comment by soaringowl2145** [comment]
It works great.  Thanks!
