### ISSUE TITLE
[Feature Request] Google+ and Facebook authentication and gamification with friends

### ISSUE THREAD

**Issue by iAn-Pinto** [TobiasBielefeld/Simple-Solitaire#38]
I am trying to implement Google+ and Facebook authentication and gamification with friends in a fork of your project, any tips help will be appreciated. Great work btw, one of the best solitaire open sources I have come across till date.

**Comment by TobiasBielefeld** [comment]
Thanks for the compliment :D But i am afraid that i can't help you, because i have zero experience with implementing social stuff. That would also be a problem for the F-Droid store, because the google+ and facebook services aren't open source.
