### ISSUE TITLE
[Bug] Small Bug on High Scores Page

### ISSUE THREAD

**Issue by Edlanta** [TobiasBielefeld/Simple-Solitaire#39]
Hi,

i have found a small Bug on High Scores Page. Somehow i managed to get a win rate greater than 100%. As i started the Game today i had a win rate of 100 % and 10 of 10 games won. After i played another Game i had a win rate of 110% and 11 of 10 games won. 

I managed to capture a Screenshot at the time i firstly noticed the issue.
[IMGUR](http://imgur.com/a/iG0Rq)

The Version i play is 3.3.5, compiled on 04.03.2017 from FDroid.

If you need some more information, feel free to ask for it.

**Comment by TobiasBielefeld** [comment]
Hi! In this version the number of games was only incremented when starting a new game, a redeal didn't increment it.  This changed in version 3.4 where Redeals count also :)
