### ISSUE TITLE
Option for change language

### ISSUE THREAD

**Issue by verdulo** [TobiasBielefeld/Simple-Solitaire#4]
Please add option for change language of the game, instead of depending on system language. It will be useful for selecting languages which are not selectable in Android, for example Esperanto (I can provide translation).

Why some strings like "Open navigation drawer" or "Menu" are marked as non-translateable?

**Comment by TobiasBielefeld** [comment]
Hi there! Thanks for the interest in my little game :D 

That's a good idea. I added the option and try to improve it in the next days. 
I would be very happy if you could provide the translation for Esperanto. (Note that I have 6 different string.xml files, one for each activity and a array.xml file which need to be translated) Do i need to do anything else before you can translate it?

I changed some non-translatable strings to translatable. But "Open navigation drawer" and "Menu" aren't used in the UI, so they don't need a translation :)

**Comment by TobiasBielefeld** [comment]
I'll make the new release for Google Play and F-Froid in a few days after some testing :)
