### ISSUE TITLE
Mar 29 '17 commit has compile error: Error:(21, 33) No resource found that matches the given name (at 'background' with value '@drawable/card_highlight').

### ISSUE THREAD

**Issue by iAn-Pinto** [TobiasBielefeld/Simple-Solitaire#40]
Mar 29 '17 commit has compile error in activity_game_manager.xml Error:(21, 33) No resource found that matches the given name (at 'background' with value '@drawable/card_highlight').

**Comment by TobiasBielefeld** [comment]
whoops, forgot to add the file to git. It should work now
