### ISSUE TITLE
Klondike game is scaled wrong after update.

### ISSUE THREAD

**Issue by JonathanMerritt** [TobiasBielefeld/Simple-Solitaire#50]
On my SGS3 the Klondike game is very small. Only while in portrait, landscape is fine.

Looking thru the commits it does seem like you changed some things there, figured I'd let you know.

**Comment by TobiasBielefeld** [comment]
Thank you very much for the feedback! I changed the scaling for some testing and forgot to revert it back to normal... I am very sorry that this happened.

I uploaded the fix to Google Play and hope it will be available soon.

**Comment by JonathanMerritt** [comment]
Nothing to worry about. Just wanted to make sure you were aware is all.

Update fixed the issue. Thanks.
