### ISSUE TITLE
Feature Request: Game rules accessible from game 

### ISSUE THREAD

**Issue by Adrien-Luxey** [TobiasBielefeld/Simple-Solitaire#57]
Hi there !

I've been using your app for some time now, and I really enjoy it, thanks! Mostly, I'm discovering new solitaires with your included rules. The only issue I have is that I need 7 clicks to go from a solitaire to its rules (back to home screen, into the manual, games rules, and finally click on the right rule). This is painful. Could a shortcut to a game's rules be included straight in the playing screen, please?

Many thanks!
Adrien

**Comment by TobiasBielefeld** [comment]
Sure this isn't a problem, I will add a new entry to the in game menu as a shortcut to the corresponding manual entry :)

**Comment by Adrien-Luxey** [comment]
Cool! I was figuring this wouldn't be too hard. ;)

**Comment by TobiasBielefeld** [comment]
Added in the now released version 3.8
