### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [TobiasBielefeld/Simple-Solitaire#59]
Hi @TobiasBielefeld 

I found [this app](https://play.google.com/store/apps/details?id=startandroid.ru.solitairepack) on the Google Play Store. This guy just took your source code and put it on the Store, without warning this is free/libre software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.

Maybe add a link to this repo in the request, some screenshots of your original app...

**Comment by TobiasBielefeld** [comment]
Thanks for showing me this app!

Sadly there are way too many copies of my game in the game store (already removed like 5)...

I sent the request, hopefully this will be removed soon :)

**Comment by TobiasBielefeld** [comment]
Well, Google said No...  "Google has decided not to take action" I think I need to ask the "developer" of the copy directly.

**Comment by Poussinou** [comment]
Google...
Yep maybe try to talk directly with him

**Comment by TobiasBielefeld** [comment]
Well the author doesn't respond, so I will close this issue.

**Comment by Poussinou** [comment]
Pity !
