### ISSUE TITLE
Highscores not saved after list becomes "full"

### ISSUE THREAD

**Issue by sbe15** [TobiasBielefeld/Simple-Solitaire#64]
While playing Vegas I observed, that from the point where all highscores are at maximum points, the highscores are no longer updated (even if, for instance, the game is completed in less time).

My guess is that [master/app/src/main/java/de/tobiasbielefeld/solitaire/helper/Scores.java](https://github.com/TobiasBielefeld/Simple-Solitaire/blob/master/app/src/main/java/de/tobiasbielefeld/solitaire/helper/Scores.java) should be:

    /**
     * Adds a new high score to the list. New score will be inserted at the last position
     * and moved left until it is in the right position
     */
    public void addNewHighScore() {
        /* ... */

        //if the new score is greater than the last saved one or the last one is empty, override it
        /*  Should this rather be "score >= savedScores[index][0]" ? */
        if (score > savedScores[index][0] || savedScores[index][0] == 0) {
            /* ... */
        }
    }

The part for inserting the new highscore seems correct, as - as far as I can tell - the time is included in the sorting.

**Comment by TobiasBielefeld** [comment]
oh thanks again :D Yes, the if condition wasn't correct. I needed to add the case "Same score, but less (or equal) time". So it will now always save the newest possible score.

I released version 3.8.4 for this :)

**Comment by sbe15** [comment]
👍
