### ISSUE TITLE
Score is increased after game is won

### ISSUE THREAD

**Issue by winjar** [TobiasBielefeld/Simple-Solitaire#66]
Occasionally score is increased after game is won. This happens, at least, with Mod3 and Golf.

Example from Mod3:

1.  One move left to win the game, score is 4550.
2.  The final move is done, score is increased to 4600.
3.  **Right away score is increased to 13797.**
4.  Menu pops up.

The increased score is save to high scores.

**Comment by TobiasBielefeld** [comment]
Well this is an intended bonus. Which is calculated with the current score and the time of that game. 
But it seems to be very much, should I decrease it?

Also I think I should make a little window after winning like "Your score: X, Bonus Y: Total: Z"

**Comment by winjar** [comment]
Oh, I didn't know about that. In that case, should the documentation mention something about the bonus?

Yeah, it seems to be a quite a jump, but that might be a bug...
Couple of results from high scores...
- Time: 00:11:30, score: 13797
- Time: 00:06:05, score 4400

**Comment by TobiasBielefeld** [comment]
okay the calculation seems to be correct. But I will change it a bit and also add some information in the manual :)

**Comment by winjar** [comment]
Sounds good. In my previous comment, the score 4400 might have been from a game which wasn't won.

**Comment by TobiasBielefeld** [comment]
Ok, I changed the calculation. The bonus in your first example would be 133 Points. If the time would be 5 minutes, the bonus would be 300. In one minute it would be 1533. So winning faster will increase the score a lot.

I hope the calculation is now better :) Then I would release the new version.

**Comment by TobiasBielefeld** [comment]
Okay I released the new version 3.8.5
