### ISSUE TITLE
Switch the position of the cards : right to left

### ISSUE THREAD

**Issue by mentalo-** [TobiasBielefeld/Simple-Solitaire#70]
I'm left handed, and it would be more practical for me to tap on the cards if they are of the left of the screen. Not only for me, but for the disabled people too, who play with only one hand. Playing with the left hand makes us hide the entire screen with our hand.

Maybe a option could switch the hidden cards from the right to the left.

**Comment by TobiasBielefeld** [comment]
Did you already try the Left Handed Option in Settings -> General?

**Comment by mentalo-** [comment]
Ooups, I have look in the settings but I never saw this option ! Sorry for this useless issue...

**Comment by TobiasBielefeld** [comment]
No problem, feel free to suggest other improvements for left handed mode, if you find anything :)
