### ISSUE TITLE
FreeCell - autocomplete too strict

### ISSUE THREAD

**Issue by matejx** [TobiasBielefeld/Simple-Solitaire#76]
Please consider making FreeCell offer autocomplete sooner. It seems to me the cards in the stacks only need to be in ascending (or equal) order. The suits don't really matter.

**Comment by TobiasBielefeld** [comment]
oh you are right, I'll change that in the next update. Thanks for reporting this!

**Comment by TobiasBielefeld** [comment]
App version 3.9 also contains this change
