### ISSUE TITLE
FreeCell - moving a stack of cards

### ISSUE THREAD

**Issue by matejx** [TobiasBielefeld/Simple-Solitaire#78]
The number of cards that can be moved seems a bit low. I've done a bit of thinking and came up with the following formula:

x = (c+1)*(1<<t);   // 1<<t == pow(2,t)

Where c is the number of free cells, and t is the number of free tableau places. Please double check this.
Would you implement this as well please?

**Comment by TobiasBielefeld** [comment]
Hi! I found this formula also here: http://www.solitairecentral.com/articles/FreecellPowerMovesExplained.html and on other websites, so it seems correct :) I will implement it in FreeCell and also in Forty&Eight and Grandfathers Clock

 Thank you very much!

**Comment by TobiasBielefeld** [comment]
i released the update as version 3.9 containing this change
