### ISSUE TITLE
google play 3.9.1 .apk is not working

### ISSUE THREAD

**Issue by alekksander** [TobiasBielefeld/Simple-Solitaire#90]
i can't install this app manually by downloading apk from play store. it says that there is an error while analyzing.
android 5.1

**Comment by TobiasBielefeld** [comment]
could you describe your method of downloading a bit more? I used the YALP store and everything worked fine.

**Comment by alekksander** [comment]
this is exactly how i'm trying to do it. apparently there has to be something wrong in my phone.

**Comment by TobiasBielefeld** [comment]
that was also my guess, glad that it works again :D
