### ISSUE TITLE
Score date changed

### ISSUE THREAD

**Issue by lkelemen** [TobiasBielefeld/Simple-Solitaire#91]
I played several klondike games yesterday and today. The date of the scores shows today's date only

**Comment by lkelemen** [comment]
![screenshot_20171201-232358](https://user-images.githubusercontent.com/11487871/33504201-37ee2d02-d6ef-11e7-8955-c639ee159182.png)

**Comment by lkelemen** [comment]
Screenshot

**Comment by TobiasBielefeld** [comment]
hmm strange, are you sure those games shortly after midnight are from the previous day? Anyway, I'll look into this :)

**Comment by lkelemen** [comment]
Hi,I played more and now I don't have those scores anymore. I suppose the easiest way would be to test this to delete the scores and set the time to a bit before midnight and play and see what happens.Best regardsLajosOn 4 Dec 2017 10:46, Tobias Bielefeld <notifications@github.com> wrote:hmm strange, are you sure those games shortly after midnight are from the previous day? Anyway, I'll look into this :)

**Comment by TobiasBielefeld** [comment]
yep I'll try that, thanks!

**Comment by lkelemen** [comment]
Hi,I've read that you plan to do a re-mix of cards functionality when there are no moves anymore. I'd like that as my score shows 30% winrate which is too low for my taste:) When will you implement this?Other option would be to mix the card so that they always give a solution. This way of shuffling could be an option in settings.ThanksLajosOn 4 Dec 2017 22:21, Tobias Bielefeld <notifications@github.com> wrote:yep I'll try that, thanks!

**Comment by TobiasBielefeld** [comment]
It's nearly finished, the next update will contain it! And the other option was also in my mind, I wanted to try to implement it after the next update :)

**Comment by lkelemen** [comment]
Thanks:)LajosOn 6 Dec 2017 15:41, Tobias Bielefeld <notifications@github.com> wrote:It's nearly finished, the next update will contain it! And the other option was also in my mind, I wanted to try to implement it after the next update :)

**Comment by TobiasBielefeld** [comment]
so I could never reproduce this issue, so I gonna close it. Hope this is okay!
