### ISSUE TITLE
[SimpleSimon] Ensure game is solvable

### ISSUE THREAD

**Issue by waldner** [TobiasBielefeld/Simple-Solitaire#93]
I don't know whether this happens with other games, but I certainly saw it in Simple Simon. In my experience, between about 1/5 and 1/6 of the generated Simple Simon games are unsolvable. This forces the user to "start new game" and a lost game is recorded in the stats.

I understand that a complete check could be very heavyweight, but I'd appreciate at least some basic checks, starting from the obvious base case where no move is possible from the very beginning - yes it happens - and perhaps checking that after 1, 2, ...N moves (for small values of N, otherwise the possibilities explode) the game doesn't reach an unsolvable state. That would already be a step forward.

Another option could be to modify the board generation algorithm to ensure it generates solvable games (perhaps starting from a solved game, then scrambling the cards "backwards" so we're sure that the initial state that is presented to the user can lead to a solved game).

Thanks

**Comment by TobiasBielefeld** [comment]
Hi, thanks for showing this issue! Using only winnable games was the next thing on my to do list. So I'll try to implement it first, before trying your other approach :)

**Comment by waldner** [comment]
Thanks!

**Comment by TobiasBielefeld** [comment]
In the mean time, until I have more time to work on the "deal only winnable games", the new app release 3.10 has an option to mix the cards on the field, excluding sequences in correct order. This should be helpful!

**Comment by waldner** [comment]
Yes, that's already an improvement. Thanks!

**Comment by waldner** [comment]
Perhaps I spoke too soon...having the option to shuffle cards in place is kind of cheating, since this way success is guaranteed, as one can just shuffle until a solvable game is found. I'm having mixed feelings on this one.

**Comment by TobiasBielefeld** [comment]
Well you could restrict yourself from using the function near game end :D But I know what you mean. I'll see how well the other solution will work

**Comment by lxkurko** [comment]
Personally, I think it's a natural part of the game that not all deals are solvable.

Option to check for solvability won't hurt, but I hope that it's not forced, and perhaps not even enabled by default.

**Comment by waldner** [comment]
Of course, but unsolvable games affects statistics negatively. Perhaps there should be an option to reset statistics.

**Comment by TobiasBielefeld** [comment]
Well there were also Google Play reviews on this topic, which gave me bad rating because too many games were not winnable... But like I said in Issue #86, this setting would also be presented in an intro screen :)

**Comment by ry4nguera** [comment]
I dont undrstnd

**Comment by TobiasBielefeld** [comment]
Hi, i am very sorry that this takes so long. I was experimenting a lot and this feature required a lot of changes in my code. but I finally found a good solution. 
I still need time to test/improve it, and my free time for that is currently really rare. So if you don't want to wait anymore you can install my current app version from the testing branch here: https://github.com/TobiasBielefeld/Simple-Solitaire/blob/testing/app/release/app-release.apk (Signed with my Google Play key)

The feature works currently like this:
* There is a new option in the general settings called "Ensure movability". enable it
* In the expert settings is the entry "Ensure movability: Amount of moves". Click on it and enter a new value for SimpleSimon or any other game
* then before every start, for a new deal, it tests if X amount of moves are possible or the game is winnable within that amount of moves. It checks deals until you cancel the process or it finds a suitable deal.
* It uses the hint function to find moves. So not every possible winnable game can be found. Especially in SimpleSimon, but I could also improve the algorithm for that a little bit.

On my phone, setting 30 moves for SimpleSimon will work pretty well, without having noticeable waiting times at a new game. Maybe it is already good enough to win most games (I never really play SimpleSimon, so i can't really tell)

**Comment by waldner** [comment]
Many thanks for your efforts! I will try the game as soon as I can.

**Comment by TobiasBielefeld** [comment]
I released a new app version with the changes, hopefully it works well enough for your needs :) I'll close this issue then
