### ISSUE TITLE
Configurable number of undo moves

### ISSUE THREAD

**Issue by waldner** [TobiasBielefeld/Simple-Solitaire#94]
Currently, it looks like the number of undoable moves is fixed to 20. I think it would be nice if this number were configurable (with perhaps 20 still being the default value).

Thanks

**Comment by TobiasBielefeld** [comment]
Hi! I think my game has already too many configurable settings, so I would just increase the number of undo moves. What do you think would be a fair amount? Maybe 50?

**Comment by waldner** [comment]
I was saying that because I suspect that a deep undo queue could waste memory, so if one doesn't want that many undo levels they could just keep it to a low number. 50 is fine for me. Regarding the "too many configurable settings", perhaps you could do a special "enable/show expert-mode settings" button or so to group less-frequently used settings, so those who don't want/need to change them won't see them. Thanks.

**Comment by TobiasBielefeld** [comment]
yea you are right, this would also be better for future settings, I'll use that approach!

**Comment by TobiasBielefeld** [comment]
The new app version 3.10  contains this now!

**Comment by waldner** [comment]
Excellent!
