### ISSUE TITLE
Tip for some icons

### ISSUE THREAD

**Issue by dankan1890** [TobiasBielefeld/Simple-Solitaire#99]
Thus, it is purely personal taste, but a couple of icons would see the best of current, for example:
Score -> https://materialdesignicons.com/icon/trophy-award
Hint -> https://materialdesignicons.com/icon/lightbulb-on
 
:)

**Comment by TobiasBielefeld** [comment]
I will test them if they fit in the app, thanks!

**Comment by TobiasBielefeld** [comment]
In my new app version 3.11 I use the lightbulb icon, but in my opinion the trophy icon is a bit too small compared to the other icons :)
